version: '3.9'

services:
  eng-ai-agents:
    build:
      context: "."
      dockerfile: ./docker/Dockerfile.dev.gpu
    image: eng-ai-agents
    platform: linux/arm64  # Ensure compatibility with Apple M1/M2/M3
    shm_size: '8gb'  # Shared memory size
    user: vscode
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - PLATFORM=macos  # Optional, in case you need to differentiate macOS-specific behaviors
    networks:
      - eng-ai-agents-net

networks:
  eng-ai-agents-net:
    driver: bridge

volumes:
  minio_data:
  rye-cache:
